name: Build and Deploy Webpage
on:
  push:
    branches: [ develop ]
  workflow_dispatch:

defaults:
  run:
    working-directory: webpage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: files
      uses: jitterbit/get-changed-files@v1
    - id: changes
      run: |
        unset DO_BUILD
        for changed_file in ${{ steps.files.outputs.all }}; do
          if  [[ ${changed_file} == "CHANGELOG.md" ]] || [[ ${changed_file} == screenshots* ]] || [[ ${changed_file} == webpage* ]] ;
          then
            echo "'${changed_file}' matches, we will build"
            DO_BUILD='true'
          fi
        done
        echo "DO_BUILD: ${DO_BUILD}"
        echo ::set-output name=DO_BUILD::${DO_BUILD}
    - if: ${{ steps.changes.outputs.DO_BUILD }}
      name: Use Node.js
      uses: actions/setup-node@v1
    - if: ${{ steps.changes.outputs.DO_BUILD }}
      run: yarn install
    - if: ${{ steps.changes.outputs.DO_BUILD }}
      run: yarn run build
