name: Build and Deploy Webpage
on:
  push:
    branches: [ develop ]
  workflow_dispatch:

defaults:
  run:
    working-directory: webpage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: files
      uses: jitterbit/get-changed-files@v1
    - id: changes
      run: |
        DO_BUILD=false
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
          if  [[ ${changed_file} == "CHANGELOG.md" ]] || [[ ${changed_file} == screenshots* ]] || [[ ${changed_file} == webpage* ]] ;
          then
              DO_BUILD=true
          fi
        done
        echo ::set-output name=DO_BUILD::${DO_BUILD}
    - if: ${{ steps.vars.outputs.DO_BUILD == false }}
      name: cancelling
      uses: andymckay/cancel-action@0.2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: yarn install
    - run: yarn run build
