name: PS-Test

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build QOwnNotes Windows Release
      shell: pwsh
      run: |
        dir .\scripts\github\windows-build-zip.ps1
        & .\scripts\github\windows-build-zip.ps1
